version: 2
jobs:
  build: 
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t ip-cloud/sbt:latest .
      - run:
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: 
          command: docker push ip-cloud/sbt:latest
